### ISSUE TITLE
Delay when Loading SVG image

### ISSUE THREAD

**Issue by johnxy84** [luberda-molinet/FFImageLoading#1129]
### Description

There's a micro second (like 2 Seconds) delay before the SVGs are loaded,  that delay ,makes the UI glitchy

### Steps to Reproduce

```
<ffimageloadingsvg:SvgCachedImage
        HeightRequest="30"
        HorizontalOptions="Start"
        WidthRequest="30"
        Source="share.svg">
</ffimageloadingsvg:SvgCachedImage>
```
### Expected Behavior

Should load up the SVG files as the page loads up

### Actual Behavior

There's a delay before the SVG actually loads up

### Basic Information

- Version with issue: 2.4.3.840
- Last known good version: 
- Platform: Xamarin.Forms: 3.2

**Comment by EmilAlipiev** [comment]
I have recognized that also especially i dont know why but when I have weak internet somewhere although svg images are locally stored, they are delayed to appear. It is very difficult to reproduce and I dont what is the relation between local svg image and internet connection

**Comment by johnxy84** [comment]
Awesome, can't wait to see it in action.

**Comment by adrianknight89** [comment]
@daniel-luberda Has the new control been merged yet? I have this delay problem on iOS. I have embedded svgs in native projects, but the first time I run the app, I'm setting the opacity of one svg to less than 1. On Android, this happens before the app is displayed to the user. On iOS, I see a noticeable visual change that sets the opacity from 1 to whatever I want to set it to.

**Comment by StevenKek** [comment]
Are there any news about this? I would love to use it in our current project.

**Comment by adrianknight89** [comment]
Possibly related #1176

**Comment by adrianknight89** [comment]
@daniel-luberda I just updated to 2.4.5.922 and noticed iOS svg performance degraded a lot. When the app is run initially, I show multiple SVGs (about 10). Previously, the performance was acceptable, but now it takes 5-7 seconds before they are rendered.

**Comment by EmilAlipiev** [comment]
@adrianknight89 is it reproducible in your sample on the other your old issue? how does it look like on Android?

**Comment by daniel-luberda** [comment]
I think I'll need to add a lock, which allows max 2 svg decoding at a time or something similar. I'll test it and let you know.

**Comment by daniel-luberda** [comment]
One more question. @adrianknight89 What device?

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/commit/9ce171fef63a308529b88456aa82724020836ee6 and https://github.com/luberda-molinet/FFImageLoading/commit/d00a8dd51d1dc810411f89745d447fbbe3e922d6

**Comment by adrianknight89** [comment]
@daniel-luberda I tested it on iPhone XS. @EmilAlipiev Android works fine. It is not reproducible on the other sample. I have a custom activity indicator that ticks every 100 ms and draws a shape when the app is launched. At the same time, the svgs are shown. So, I'm guessing this could be a timer-related issue along with the recent changes.

**Comment by daniel-luberda** [comment]
@adrianknight89 

https://github.com/luberda-molinet/FFImageLoading/commit/9ce171fef63a308529b88456aa82724020836ee6 and https://github.com/luberda-molinet/FFImageLoading/commit/d00a8dd51d1dc810411f89745d447fbbe3e922d6

should definitely help as decoding operation is a resource heavy operation. There was no limit at all for SVG files which means that up to 16 could take place at once and supposedly could generate a lag.

**Comment by daniel-luberda** [comment]
It should be fixed with the latest stable. Please let me know if it's not working for you.

**Comment by johnxy84** [comment]
After I updated to the Latest Version, My Svgs stopped rendering altogether.
Version => 2.4.6.929
Xamarin.Forms Version => 3.6.0.344457

**Comment by daniel-luberda** [comment]
Please update to 2.4.7.944 stable or 2.4.7.938-prerelease, there was an issue on Android.

**Comment by johnxy84** [comment]
Yeah. Version 2.4.7.944 Fixes it.

**Comment by pji33250** [comment]
Hey, I am glad to find this link, I had exactly the same issue, and I still get slow (delay) on my iPhone, I have tried all versions.
Checked all possible sources....Init, included all the Xamarim.FFImageLoading.*
Attached is like my HomePage, everything displayed except the svg image when the home page is up; it takes about 8-9 seconds, then the svg image shows
Currently, Xamarin version is 3.6.0.344457 (I have tried 4.0, it is the same)
Xamarin.FFImageLoading.* version is 2.4.11.982
Thanks

Here is my xaml file, the svg file I used is from local

<?xml version="1.0" encoding="UTF-8"?>
<base:BasePage 
    xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
    xmlns:base="clr-namespace:PatientApp.Features.Base;assembly=PatientApp"
    xmlns:controls="clr-namespace:PatientApp.UI.Controls;assembly=PatientApp"
    xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms" prism:ViewModelLocator.AutowireViewModel="True"
    xmlns:svg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"
    x:Class="PatientApp.Features.Home.HomePage"
    AnimateRing="{Binding AnimateRing}"
    HasSendTransmissionButton="{Binding HasSendTransmissionButton}"
    ControlTemplate="{StaticResource MainPageTemplate}">

    <ScrollView 
        VerticalOptions="FillAndExpand"
        Orientation="Vertical"
        BackgroundColor="{StaticResource LighGrey}">
        
        <StackLayout 
            Orientation="Vertical">

            <Grid x:Name="transmitterStatusGrid" 
                  BackgroundColor="{StaticResource Navigation_Background}"
                  Padding="0,8,0,8">

                <Grid.RowDefinitions>
                    <RowDefinition Height="140" />
                </Grid.RowDefinitions>

                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*"/>
                    <ColumnDefinition Width="2*"/>
                    <ColumnDefinition Width="*"/>
                </Grid.ColumnDefinitions>

                <svg:SvgCachedImage 
                    AutomationId="Home_DeviceCheckImage"
                    Grid.Row="0"
                    Grid.Column="1" 
                    Aspect="AspectFit"
                    Margin="0"
                    Source="heart_device_checked.svg" />
                
            </Grid>
            <StackLayout 
                Orientation="Vertical"
                Padding="0,-8,0,0">

                <StackLayout 
                    Orientation="Vertical"
                    Padding="10,10,10,20"
                    BackgroundColor="{StaticResource Navigation_Background}">

                    <Label
                        AutomationId="Home_PrimaryMessageText"
                        HorizontalOptions="CenterAndExpand"
                        VerticalOptions="EndAndExpand"
                        HorizontalTextAlignment="Center"
                        Margin="10,0,10,0"
                        Text="{Binding PrimaryMessageText}"
                        TextColor="{StaticResource Text_Inverse}"
                        FontSize="{StaticResource Text_Xlg}"
                        FontAttributes="Bold"/>
                    <Label
                        AutomationId="Home_SecondaryMessageText"
                        HorizontalOptions="CenterAndExpand"
                        VerticalOptions="StartAndExpand"
                        HorizontalTextAlignment="Center"
                        Margin="10,0,10,10"
                        Text="{Binding SecondaryMessageText}"
                        TextColor="{StaticResource Text_Inverse}"
                        FontSize="{StaticResource Text_Med}"/>
                </StackLayout>
                <controls:StatefulButton 
                    AutomationId="Home_TryAgainButton"
                    HeightRequest="40"
                    Margin="10,-26,10,0"
                    IsEnabled="{Binding ConnectNowButtonEnabled}"
                    IsVisible="{Binding ConnectNowButtonVisible}"
                    Text="{Binding ConnectNowButtonText}"
                    Command="{Binding ConnectNowCommand}"
                    EnabledStyle="{StaticResource PrimarySolid_Enabled}"
                    DisabledStyle="{StaticResource PrimarySolid_Disabled}"/>
                
                <StackLayout 
                    x:Name="navButtonStackLayout"
                    HorizontalOptions="StartAndExpand"
                    VerticalOptions="FillAndExpand">
                </StackLayout>
            </StackLayout>
        </StackLayout>
    </ScrollView>
</base:BasePage>

**Comment by aftab-currency** [comment]
> Hey, I am glad to find this link, I had exactly the same issue, and I still get slow (delay) on my iPhone, I have tried all versions.
> Checked all possible sources....Init, included all the Xamarim.FFImageLoading.*
> Attached is like my HomePage, everything displayed except the svg image when the home page is up; it takes about 8-9 seconds, then the svg image shows
> Currently, Xamarin version is 3.6.0.344457 (I have tried 4.0, it is the same)
> Xamarin.FFImageLoading.* version is 2.4.11.982
> Thanks
> 
> Here is my xaml file, the svg file I used is from local
> 
> <base:BasePage
> xmlns="http://xamarin.com/schemas/2014/forms"
> xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
> xmlns:base="clr-namespace:PatientApp.Features.Base;assembly=PatientApp"
> xmlns:controls="clr-namespace:PatientApp.UI.Controls;assembly=PatientApp"
> xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms" prism:ViewModelLocator.AutowireViewModel="True"
> xmlns:svg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"
> x:Class="PatientApp.Features.Home.HomePage"
> AnimateRing="{Binding AnimateRing}"
> HasSendTransmissionButton="{Binding HasSendTransmissionButton}"
> ControlTemplate="{StaticResource MainPageTemplate}">
> 
> ```
> <ScrollView 
>     VerticalOptions="FillAndExpand"
>     Orientation="Vertical"
>     BackgroundColor="{StaticResource LighGrey}">
>     
>     <StackLayout 
>         Orientation="Vertical">
> 
>         <Grid x:Name="transmitterStatusGrid" 
>               BackgroundColor="{StaticResource Navigation_Background}"
>               Padding="0,8,0,8">
> 
>             <Grid.RowDefinitions>
>                 <RowDefinition Height="140" />
>             </Grid.RowDefinitions>
> 
>             <Grid.ColumnDefinitions>
>                 <ColumnDefinition Width="*"/>
>                 <ColumnDefinition Width="2*"/>
>                 <ColumnDefinition Width="*"/>
>             </Grid.ColumnDefinitions>
> 
>             <svg:SvgCachedImage 
>                 AutomationId="Home_DeviceCheckImage"
>                 Grid.Row="0"
>                 Grid.Column="1" 
>                 Aspect="AspectFit"
>                 Margin="0"
>                 Source="heart_device_checked.svg" />
>             
>         </Grid>
>         <StackLayout 
>             Orientation="Vertical"
>             Padding="0,-8,0,0">
> 
>             <StackLayout 
>                 Orientation="Vertical"
>                 Padding="10,10,10,20"
>                 BackgroundColor="{StaticResource Navigation_Background}">
> 
>                 <Label
>                     AutomationId="Home_PrimaryMessageText"
>                     HorizontalOptions="CenterAndExpand"
>                     VerticalOptions="EndAndExpand"
>                     HorizontalTextAlignment="Center"
>                     Margin="10,0,10,0"
>                     Text="{Binding PrimaryMessageText}"
>                     TextColor="{StaticResource Text_Inverse}"
>                     FontSize="{StaticResource Text_Xlg}"
>                     FontAttributes="Bold"/>
>                 <Label
>                     AutomationId="Home_SecondaryMessageText"
>                     HorizontalOptions="CenterAndExpand"
>                     VerticalOptions="StartAndExpand"
>                     HorizontalTextAlignment="Center"
>                     Margin="10,0,10,10"
>                     Text="{Binding SecondaryMessageText}"
>                     TextColor="{StaticResource Text_Inverse}"
>                     FontSize="{StaticResource Text_Med}"/>
>             </StackLayout>
>             <controls:StatefulButton 
>                 AutomationId="Home_TryAgainButton"
>                 HeightRequest="40"
>                 Margin="10,-26,10,0"
>                 IsEnabled="{Binding ConnectNowButtonEnabled}"
>                 IsVisible="{Binding ConnectNowButtonVisible}"
>                 Text="{Binding ConnectNowButtonText}"
>                 Command="{Binding ConnectNowCommand}"
>                 EnabledStyle="{StaticResource PrimarySolid_Enabled}"
>                 DisabledStyle="{StaticResource PrimarySolid_Disabled}"/>
>             
>             <StackLayout 
>                 x:Name="navButtonStackLayout"
>                 HorizontalOptions="StartAndExpand"
>                 VerticalOptions="FillAndExpand">
>             </StackLayout>
>         </StackLayout>
>     </StackLayout>
> </ScrollView>
> ```
> 
> </base:BasePage>

We're also getting the same issue with 2.4.11.982. On iOS app, everything displayed except the svg image on startup. It takes around 10 seconds.

@pji33250 do you found any workaround for this?

**Comment by khoangt** [comment]
I had also getting the same issue with 2.4.11.982

**Comment by nbloms** [comment]
I'm having the same issue, on physical devices only (only tried on iPad pro), simulator works fine. 
On version 2.4.11.982. 
Xamarin.Forms version 4.8.0.1687
@daniel-luberda since this has been closed for some time. Should a new issue be opened instead?
