### ISSUE TITLE
2.4.8.956 version Svg Problem

### ISSUE THREAD

**Issue by EmilAlipiev** [luberda-molinet/FFImageLoading#1264]
### Description
 

Most of my Svgs became problematic after upgrading to the latest version. i am attaching one of the svg with problem 

version 2.4.8.956 
![image](https://user-images.githubusercontent.com/10422347/57253879-1b58a680-7050-11e9-8a54-2b2adb44c833.png)

earlier versions

![image](https://user-images.githubusercontent.com/10422347/57254238-0b8d9200-7051-11e9-86f2-a4fc3ff5fe8e.png)

[main_wizard.zip](https://github.com/luberda-molinet/FFImageLoading/files/3149768/main_wizard.zip)
 

### Basic Information

- Version with issue: 2.4.8.956
- Last known good version: all previous versions
- Platform: UWP desktop, Android

**Comment by daniel-luberda** [comment]
Fixed :)

**Comment by EmilAlipiev** [comment]
thank let me know when you make a new release i will test again asap

**Comment by daniel-luberda** [comment]
released

**Comment by EmilAlipiev** [comment]
still not working on version 2.4.11.982. it solves the problem with missing circle around but my svg has black background, it removes it and makes it transparent.

**Comment by EmilAlipiev** [comment]
I have now tested versions before and actually none of them really works. last working version was 2.4.5.870-pre  and this version doesnt seem to be in Nuget any longer. i dont know how to restore to that version.

**Comment by Alextorres950325** [comment]
same error here
