### ISSUE TITLE
Support for Authentication tokens/headers?

### ISSUE THREAD

**Issue by ravensorb** [luberda-molinet/FFImageLoading#173]
Any thought to support Authentication tokens and/or headers during the request process?  For example, how would I set an OAuth Bearer token priory to using this in XAML on a page?  Keeping in mind that authentication will happen long after the application loads (in terms of start up).  

One possible option could be to allow a callback (Action/Func type property) to be set within the PCL code?

Ex:
```c#
ImageService.InitializeClient = (httpClient) => 
{ 
    httpClient.DefaultRequestHeaders.Add("Authorization", "Bearer XXXXXXXXX");
};
```

**Comment by ravensorb** [comment]
Note: I tried setting a custom HttpClient in the Initialize method -- this does not work.  I get a general error back and since FFImageLoading hides the underlying error, I have no idea what went wrong.

**Comment by michaeldimoudis** [comment]
Hi, I have gotten authentication support working. Please find a few tips below :)

In your AppDelegate or MainActivity:
`ImageService.Initialize(new Configuration
{
	HttpClient = new HttpClient(new AuthenticatedHttpImageClientHandler(_authService.GetToken))
});`

And something like this for the auth handler:
`namespace MyNamespace
{
    public class AuthenticatedHttpImageClientHandler : HttpClientHandler
    {
        private readonly Func<Task<string>> _getToken;`

        public AuthenticatedHttpImageClientHandler(Func<Task<string>> getToken)
        {
            if (getToken == null) throw new ArgumentNullException("getToken");
            _getToken = getToken;
        }

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            request.Headers.Add("Authorization", "Bearer " + token);
            return await base.SendAsync(request, cancellationToken).ConfigureAwait(false);
        }
    }
`}`

**Comment by ravensorb** [comment]
Thanks.  However, I tried almost exactly that :)  All I get is a general error generating image with no additional information in both the Logger or the Error Event Handler.

Note: Mine is a little different as I don't get a token until after the login process which is long after the MainActivity initializes.  

I also tried setting the DefaultHeaders in HttpClient in the Download Cache Handler and that also didn't work.

if I switch to just a simple HttpClient with setting he default headers and downloading the image manually it works perfectly.  

I'll try your exact code and see if that works though.

**Comment by ravensorb** [comment]
Yep, just to confirm -- using the EXACT code above with an addition of calling 

    token = await _getToken();

I get the same thing 

    e.Exception	{"FFImageLoading is unable to generate image."}	System.Exception

I have tried with 2.0.7.1 and with 2.1.0-alpha1  -- both result in the same thing with NO additional error information, so I have no idea why it is failing. And since I cannot get the current code branch to build, debugging is turning out to be all but impossible.

**Comment by daniel-luberda** [comment]
Hi @ravensorb @michaeldimoudis,

@ravensorb That error is probably TaskCancelledException, I fixed it here: https://github.com/molinch/FFImageLoading/commit/f87602abd6f17dc78f8d25418b509535b150d2e7#diff-7399e835b4d01addca6bd9a204466d58R213

**Comment by molinch** [comment]
FFImageLoading 2.1.0-alpha2 nuget released which brings this fix.
Could you please have a look at it?

**Comment by molinch** [comment]
@ravensorb Any news about it? 2.1 RC2 is now released.

**Comment by ravensorb** [comment]
Trying to update now -- running into odd issues with my UWP project at the moment.  It is complaining that FFImageLoading is defined in multiple assemblies.  Plus I am still getting the corrupt data error

```
Unable to read package from path 'Xamarin.FFImageLoading.Forms.2.1.0-rc2\Xamarin.FFImageLoading.Forms.2.1.0-rc2.nupkg'.
  File contains corrupted data.
```

**Comment by molinch** [comment]
I really don't get it: on my side the package works as a charm.
@daniel-luberda Maybe it is VS/UWP related, what do you think?

**Comment by ravensorb** [comment]
I am looking at the nuspec files now -- there are a number of small tweaks I think we can make to fix this.  If it works, I'll do a PR

**Comment by ravensorb** [comment]
Question -- Anyone know if the nuspec files and the solution in sync? I see references to FFImageLoading.Common in the nuspec files, however in the solution that project is not loaded at all + the MakeFileWindows.bat doesn't build it either so I am not sure which is correct -- the nuspec or the sln file?

**Comment by ravensorb** [comment]
Ok, running into issues :)  Is the nuspec file in the repository correct? And does it match the current source code and solution?  I am getting compiler errors on several of the samples and the nuspec file is looking for files that do not get build.

**Comment by ravensorb** [comment]
Ok, I think I found it -- looks like a bit of a classic mistake between windows and non-windows.  The nuget spec actually requires a \ to be used for path separators rather than / (doesn't matter which platform you use to create the package the xml file requires a backslah).  If I replace all of the / with \ then bingo we have a valid nuget package that passes all tests

**Comment by molinch** [comment]
Many thanks @ravensorb for the investigation!
Would you mind submitting a PR?

**Comment by ravensorb** [comment]
finished it up now

**Comment by ravensorb** [comment]
Ok, done.  I also combined the windows package into the main one.  If that is not ok, it is easy enough to pull out again.

**Comment by molinch** [comment]
@ravensorb Could you tell us if you still have this issue with 2.1.1 https://www.nuget.org/packages/Xamarin.FFImageLoading/2.1.1-pre1?
If that's the case I will investigate.

**Comment by molinch** [comment]
@ravensorb If you manage to deliver a sample we will investigate this issue.
Meanwhile there is nothing we can do about it.
