### ISSUE TITLE
Xamarin.Forms iOS - 2.2.1 version does not show images from Asset Catalogs

### ISSUE THREAD

**Issue by alexpetin** [luberda-molinet/FFImageLoading#355]
Xamarin.Forms.Image & CachedImage v2.1.8 - show these images correctly.

**Comment by daniel-luberda** [comment]
It's fixed here: https://github.com/luberda-molinet/FFImageLoading/commit/f475d628f1a8bd65467dee8d7720bc7ecbfb942b

I'll release it today.

**Comment by alexpetin** [comment]
v2.2.2 - the problem not fixed.

**Comment by daniel-luberda** [comment]
Could you give more details?

**Comment by daniel-luberda** [comment]
Could you try 2.2.3 prerelease?

**Comment by alexpetin** [comment]
2.2.3 release - the problem not fixed.

Asset Catalog Image Sets [Preferred] - Added in iOS 7, Asset Catalogs Image Sets contain all the versions or representations of an image that are necessary to support various devices and scale factors for your application. Instead of relying on the image assets filename (see the Resolution Independent Images and Image Nomenclature), Image Sets use a Json file to specify which image belongs to which device and/or resolution. This is the preferred way to manage and support images in iOS 9 (or greater).

https://developer.xamarin.com/guides/ios/application_fundamentals/working_with_images/displaying-an-image/#adding-assets

Xamarin.Forms.Image and FFImageLoading.Forms.CachedImage v2.1.8 shows images from the Asset Catalog. v2.2.1 and later - does not show (shows empty or ErrorPlaceholder image).

**Comment by daniel-luberda** [comment]
Could you test 2.2.4 prerelease and see if it's working? Thanks.

**Comment by alexpetin** [comment]
Yes, it's working - v.2.2.4-pre-201.
Thank you!

**Comment by france-launchlabs** [comment]
I confirm this is working on latest pre-release 2.2.10-pre-408. The latest stable 2.2.9  was not working when I tried to load from Assets.
