### ISSUE TITLE
Unable to add custom headers to HttpClient

### ISSUE THREAD

**Issue by almostchristian** [luberda-molinet/FFImageLoading#477]
My application uses authenticated Web API endpoints using OAuth bearer tokens to retrieve images. I created a class AuthenticatedHttpClient which would add the Authorization header when contacting the endpoints.

```
public class AuthenticatedHttpClient : System.Net.Http.HttpClient
{
    public override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        var token = await AccessTokenService.GetAccessToken();
        if (token != null)
        {
            request.Headers.Remove("Authorization");
            request.Headers.TryAddWithoutValidation("Authorization", "Bearer " + token);

            return await base.SendAsync(request, cancellationToken);
        }
        else
        {
            return new HttpResponseMessage(System.Net.HttpStatusCode.Forbidden);
        }
    }
....

ImageService.Instance.Initialize(new FFImageLoading.Config.Configuration
{
    HttpClient = new AuthenticatedHttpClient()
});
```

However, FFImageLoading never reaches SendAsync, I suspected that this override of SendAsync is never called, however I see that GetAsync(Uri, HttpCompletionOption, CancellationToken) is called, which calls SendAsync(HttpRequestMessage, HttpCompletionOption, CancellationToken) which should call SendAsync(HttpRequestMessage, CancellationToken).

For some reason, my override of SendAsync is never called and I never get to inject my custom headers. However, if I omit the HttpCompletion parameter from DownloadAsync (DownloadCache.cs) or change it to HttpCompletionOption.ResponseContentRead, my overridden method gets called.

Is there another way to inject custom headers to get around this issue? One way for me to avoid the issue would be to call initialize every time my Access Token changes.

**Comment by viktorgt** [comment]
Same issue here, using version 2.2.8
I implemented the HttpClientHandler like described on wiki but my override of SendAsync is never called.
https://github.com/luberda-molinet/FFImageLoading/wiki/Authentication-Support

**Comment by daniel-luberda** [comment]
- Do you call `ImageService.Instance.Initialize` on app startup or later?
- You should override `GetAsync`, not `SendAsync`, look here: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Common/Cache/DownloadCache.cs#L96

We had a bug on WIKI. I fixed that. WIKI is open for everyone, you can also add your comments there.

**Comment by viktorgt** [comment]
I call ImageService.Instance.Initialize inside of MainActivitiy.onCreate before instantiating the forms app.
```
base.OnCreate(bundle);
CachedImageRenderer.Init();
ImageService.Instance.Initialize(new Configuration
{
    HttpClient = new HttpClient(new AuthenticatedHttpClientHandler()),
});
global::Xamarin.Forms.Forms.Init(this, bundle);
LoadApplication(new App());
```

The System.Net.Http.HttpClientHandler has no GetAsync method. IMO, SendAsync should be correct, since I'm using the AuthenticatedHttpClientHandler for all other HttpClients to make requests to my webservice, which requires the access token in the header.

**Comment by viktorgt** [comment]
Finally I managed it. I did not attached the CacheImage into a view container, just instantiated it on code-behind for testing purpose, what obviosly does not work, since it seems to loading the image only as soon as it is visible (or part of the view?). The wiki entry should be reverted, since it was correct before ;)

**Comment by daniel-luberda** [comment]
> The wiki entry should be reverted, since it was correct before ;)

@viktorgt Yes... Sorry for misleading :) It's nice that you get it workings. Cheers.

**Comment by SagarPanwala** [comment]
I'm still facing the issue with iOS, 
FFImageLoading 2.3.6
Xamarin.Forms 2.5.0.121934

SendAsync never called for iOS, for Android it is called.

@viktorgt  : Can you please tell me what do you mean  by "attached the CacheImage into a view container" ?

**Comment by cansado2930** [comment]
Hello, 
Could you help me with this? I need to add the "host" and userAgent on each request and I can't get it works
