### ISSUE TITLE
Thread dead lock when changing the imagesource very fast

### ISSUE THREAD

**Issue by escamoteur** [luberda-molinet/FFImageLoading#554]
I observed a randomg freeze of my App. After some research I found that it seems that two threads inside ffimageloading deadlock.

![](http://res.cloudinary.com/escamoteur/image/upload/v1490688967/ffimagethreads_tytld8.png)

in my case I have assigned an IMagesource in Xaml and replace it imediately after the Page appears.

**Comment by AndreiMisiukevich** [comment]
Really, This error occurs.
I tested on Android, Xiaomi Redmi 4  (Android 6.0) - _Heavy List example_
So, app will freeze, if user starts to scroll fastly.

**Comment by daniel-luberda** [comment]
It should be fixed with the newest prerelease nuget. Could you check it?

**Comment by EmilAlipiev** [comment]
I have this problem also. is it already fixed? which version has the fix? I am using version 2.2.9

**Comment by AndreiMisiukevich** [comment]
@EmilAlipiev

You should use the latest PRErelease package.
You need to enable pre-release pachages channel.

**Comment by EmilAlipiev** [comment]
Hi I tried latest pre Release and it still occurs for me. I dont know if it is deadlock but when i scroll fast within ListView,  list gets frozen and i get message that app is not responding. Do you have any Suggestion please?

**Comment by daniel-luberda** [comment]
Should be fixed in the newest prerelease. Please reopen if it still occurs.
