### ISSUE TITLE
[Xamarin.Forms] Problem loading SVG image on iOS

### ISSUE THREAD

**Issue by marlonconstante** [luberda-molinet/FFImageLoading#604]
I'm using the latest prerelease available **Xamarin.FFImageLoading.Svg.Forms 2.2.10-pre-390** together with **Xamarin.Forms 2.3.4.231**.

**Here is the XAML code used:**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:ffimageloadingsvg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"
    x:Class="App.Views.MainPage">
    <ContentPage.Content>
        <ffimageloadingsvg:SvgCachedImage
                        WidthRequest="200"
                        HeightRequest="200"
                        Source="http://s.cdpn.io/3/kiwi.svg"/>
    </ContentPage.Content>
</ContentPage>
```

**Error:**

> Xamarin.Forms.Xaml.XamlParseException: Position 13:14. Type ffimageloadingsvg:SvgCachedImage not found in xmlns clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms
---------------------------
To solve the problem here it was necessary to reference the SvgCachedImage assembly in the AppDelegate:

```csharp
var svgAssembly = typeof(SvgCachedImage).GetTypeInfo().Assembly;
CachedImageRenderer.Init();
```

The same was not needed on Android.
Everything worked as expected.

**Comment by ericruelas** [comment]
how did you reference it?

**Comment by marlonconstante** [comment]
_Follow implementation:_

```csharp
public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate
{
	public override bool FinishedLaunching(UIApplication app, NSDictionary options)
	{
        	global::Xamarin.Forms.Forms.Init();

        	var svgAssembly = typeof(SvgCachedImage).GetTypeInfo().Assembly;
        	CachedImageRenderer.Init();

		LoadApplication(new App());

		return base.FinishedLaunching(app, options);
	}
}
```

**Comment by daniel-luberda** [comment]
It's because Xamarin's linker, it cuts the class. I'll try to add `Preserve` attributes to all classes, maybe it would help. @marlonconstante solution is the right one for such cases too (thanks).

**Comment by stmax82** [comment]
Could you please let us know what version this was fixed in? (Milestone)

The latest Nuget package doesn't seem to contain the fix yet.. I had to add var _ = typeof(SvgCachedImage); to make it work.

**Comment by daniel-luberda** [comment]
It's already included, it should work, but unluckily I can't control linker behaviour. If anyone has an idea what we could do, please let me know.

**Comment by eusebiu** [comment]
Created a bug into Xamarin bug tracking system as the Release build is different than the Debug one.
https://bugzilla.xamarin.com/show_bug.cgi?id=60653

**Comment by eusebiu** [comment]
I solved it by adding
FFImageLoading.Svg.Forms.SvgCachedImage.Init();
In any case, since "var ignore = typeof(FFImageLoading.Svg.Forms.SvgCachedImage);" was present, I think there is still an issue in the Release build in Xamarin.
