### ISSUE TITLE
"twitching" icons on iOS in view cell

### ISSUE THREAD

**Issue by kspearrin** [luberda-molinet/FFImageLoading#772]
I have a Xamarin.Forms view cell with a CachedImages that have their source bound from `OnBindingContextChanged`. See code here: 

- https://github.com/bitwarden/mobile/blob/master/src/App/Controls/LabeledDetailCell.cs#L11
- https://github.com/bitwarden/mobile/blob/master/src/App/Controls/VaultListViewCell.cs#L37

This works as expected, however, on iOS some icons are animating (twitching) when they come onto screen. It's kind of hard to explain, so I made a quick video: [twitching.zip](https://github.com/luberda-molinet/FFImageLoading/files/1403758/twitching.zip) . Notice the Code Academy, Code School, Linked In, Great American Cookie Co, and GitHub icons in the listing.

No such problem exists on Android. I should also note that these are remote images loaded from https://...

This only happened when I upgraded from v2.2.9 to v2.2.20 (latest). I downgraded back to v2.2.9 and the problem went away.

**Comment by daniel-luberda** [comment]
IMO It looks like some Xamarin.Forms layout system / `Grid` issue. What you could try is this: https://github.com/luberda-molinet/FFImageLoading/issues/545

Did you try it?

BTW: Shouldn't this: 

```C#
                Icon.Source = item.Icon;
                if(item.Type == Enums.CipherType.Login)
                {
                    Icon.LoadingPlaceholder = "login.png";
                }
```

be

```C#
                if(item.Type == Enums.CipherType.Login)
                {
                    Icon.LoadingPlaceholder = "login.png";
                }
                Icon.Source = item.Icon;
```
?

**Comment by kspearrin** [comment]
Setting `CachedImage.FixedOnMeasureBehavior = true;` does not seem to fix the problem. On the `LoadingPlaceholder` comment, does order really matter?

**Comment by daniel-luberda** [comment]
@kspearrin Is it possible to get a repo? 
 
>On the LoadingPlaceholder comment, does order really matter?

Yes, the order matters as setting `Source` starts image loading task, and it won't have `Placeholder` assigned yet, so the loading placeholder won't be enabled.

**Comment by kspearrin** [comment]
I don't have any other repo available with the problem at this time. The one linked is a pretty standard X.F project. Are you not able to get it working? I'd be happy to walk you through it if necessary.

I'll update the order of the loading placeholder. Thanks for the info on that.

**Comment by daniel-luberda** [comment]
I would prefer to have some minimal project with a reproduction (the project requires API, etc). It looks like some kind of Xamarin layout issue for me.

**Comment by daniel-luberda** [comment]
@kspearrin  Could you check if it's solved in 2.2.25?

**Comment by kspearrin** [comment]
@daniel-luberda I've had this sitting in my inbox to reply to once I upgrade, but haven't had the time yet. I will report back when I do.

**Comment by daniel-luberda** [comment]
Ok, I'll reopen as soon as I have some more info. Cheers :)

**Comment by kspearrin** [comment]
@daniel-luberda I updated to 2.2.25 and this is still a problem. Should be re-opened.
