### ISSUE TITLE
Xamarin.Forms - LoadingPlaceholder not always shown on initial loading

### ISSUE THREAD

**Issue by chaselal** [luberda-molinet/FFImageLoading#873]
### Description
Some CachedImages skip LoadingPlaceholder and go straight to Source when LoadingPlaceholder is a FileImageSource and Source is a UriImageSource. It seems to only happen to CachedImages visible when the page loads.

### Steps to Reproduce
1. Run the repro project on Android or iOS
2. Don't scroll

### Expected Behavior
Each CachedImage displays the LoadingPlaceholder image, and then downloads and displays the Source image.

### Actual Behavior
Most CachedImages do what's expected. Some skip the LoadingPlaceholder and go straight to downloading and displaying the Source image. This results in some CachedImages showing nothing at all, until their Source image has been downloaded. This is more noticeable when the Source image takes a long time to download.

### Basic Information
- Version with issue: v2.3.1, v2.2.25
- Last known good version: N/A
- Platform: Android and iOS

### Screenshots
![bug-ffimageloading](https://user-images.githubusercontent.com/3928875/34323554-f60d02e2-e813-11e7-91b6-bea99e401a59.gif)

This gif shows the problem manifest in the second and third list items.

### Reproduction Link / Code
https://github.com/chaselal/ffimageloading-issue

The FFImageLoading cache is cleared during app start up, because the problem is not noticeable if the Source images are already cached.

**Comment by daniel-luberda** [comment]
It's because your views don't have any sizes set initially, so the placeholder is not shown as it's not a destination image. You must at least set width or height and it'll working fine. I'll try to review code if we can do something about it.

**Comment by chaselal** [comment]
@daniel-luberda That doesn't seem to be the problem. I set lots of properties related to height/width, but the problem persists. See https://github.com/chaselal/ffimageloading-issue/blob/810978c7526ec69ae38d794e2c25ba87bdc50c10/Issue872.Pcl/MainPage.xaml#L19-L30

**Comment by daniel-luberda** [comment]
It was related to view size, but I fixed it (please review my commit). Should work fine now. Thank you for such a detailed info! :) It was very useful for me.

**Comment by chaselal** [comment]
I reviewed by posting single comments at https://github.com/luberda-molinet/FFImageLoading/commit/8c2ed921624908f3dc8826814099441841a23084. I did not test the fix yet.

Thanks for this, @daniel-luberda.

**Comment by chaselal** [comment]
@daniel-luberda I just updated to Xamarin.FFImageLoading and Xamarin.FFImageLoading.Forms v2.3.2 and tested on a Samsung Galaxy S7, an Android tablet emulator, and an iPad Air 2 simulator. I see the same result as before. It seems the problem is not fixed in v2.3.2.

**Comment by daniel-luberda** [comment]
Did you clean all bin/obj folders before testing and made sure that you have the same package version in all projects?

**Comment by chaselal** [comment]
> Did you clean all bin/obj folders before testing and made sure that you have the same package version in all projects?

Yes. I also updated [the repro repository](https://github.com/chaselal/ffimageloading-issue), deleted my local copy, cloned the repository again, and built from that. The problem is still there.

**Comment by chaselal** [comment]
@daniel-luberda I believe the problem can also happen in this case:
* Load a list with CachedImages. Use the RecycleElement caching strategy, Each CachedImage should have its LoadingPlaceholder and Source set. Source should be a Uri source to an image that takes a long time to download. LoadingPlaceholder should be an embedded resource or file source.
* Fling down the list
* Stop scrolling long enough for the visible items to load their Source images
* Scroll up the list. On the way, notice that items coming into view display the Source images of the items that loaded while scrolling was stopped, instead of showing their own LoadingPlaceholder. In other words, the items don't show their LoadingPlaceholder when the ListView recycles them and instead they show whatever was loaded before the ListView recycled them.

I don't have a repro project for this case. I noticed it in my closed-source app.

**Comment by chaselal** [comment]
Oops, actually v2.3.2 did fix the issue for me. I just forgot that I left out some image files used as placeholders in the repro app. I think I originally did that so the placeholder loading would fail for the second and third list items (index 1 and 2). Anyway, I can confirm that the problems described in the original post and in https://github.com/luberda-molinet/FFImageLoading/issues/873#issuecomment-354149699 are fixed now. So there's no need to open the issue again.

Thanks for fixing this so soon. I apologize for the confusion.

**Comment by daniel-luberda** [comment]
I can't reproduce it, maybe it's because you're missing some placeholder files: 

```
Setting placeholder failed
System.IO.FileNotFoundException: disk3.png
  at FFImageLoading.DataResolvers.ResourceDataResolver.Resolve (System.String identifier, FFImageLoading.Work.TaskParameter parameters, System.Threading.CancellationToken token) [0x0005b] in C:\projects\ffimageloading\source\FFImageLoading.Droid\DataResolvers\ResourceDataResolver.cs:29 
  at FFImageLoading.DataResolvers.WrappedDataResolver+<Resolve>d__2.MoveNext () [0x00020] in C:\projects\ffimageloading\source\FFImageLoading.Common\DataResolvers\WrappedDataResolver.cs:22 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <657aa8fea4454dc898a9e5f379c58734>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <657aa8fea4454dc898a9e5f379c58734>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <657aa8fea4454dc898a9e5f379c58734>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <657aa8fea4454dc898a9e5f379c58734>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <657aa8fea4454dc898a9e5f379c58734>:0 
  at FFImageLoading.Work.ImageLoaderTask`3+<ShowPlaceholder>d__107[TDecoderContainer,TImageContainer,TImageView].MoveNext () [0x00299] in C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:445 
Setting placeholder failed
System.IO.FileNotFoundException: disk2.png
  at FFImageLoading.DataResolvers.ResourceDataResolver.Resolve (System.String identifier, FFImageLoading.Work.TaskParameter parameters, System.Threading.CancellationToken token) [0x0005b] in C:\projects\ffimageloading\source\FFImageLoading.Droid\DataResolvers\ResourceDataResolver.cs:29 
  at FFImageLoading.DataResolvers.WrappedDataResolver+<Resolve>d__2.MoveNext () [0x00020] in C:\projects\ffimageloading\source\FFImageLoading.Common\DataResolvers\WrappedDataResolver.cs:22 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <657aa8fea4454dc898a9e5f379c58734>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <657aa8fea4454dc898a9e5f379c58734>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <657aa8fea4454dc898a9e5f379c58734>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <657aa8fea4454dc898a9e5f379c58734>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <657aa8fea4454dc898a9e5f379c58734>:0 
  at FFImageLoading.Work.ImageLoaderTask`3+<ShowPlaceholder>d__107[TDecoderContainer,TImageContainer,TImageView].MoveNext () [0x00299] in C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:445 
Setting placeholder failed
System.IO.FileNotFoundException: disk3.png
  at FFImageLoading.DataResolvers.ResourceDataResolver.Resolve (System.String identifier, FFImageLoading.Work.TaskParameter parameters, System.Threading.CancellationToken token) [0x0005b] in C:\projects\ffimageloading\source\FFImageLoading.Droid\DataResolvers\ResourceDataResolver.cs:29 
  at FFImageLoading.DataResolvers.WrappedDataResolver+<Resolve>d__2.MoveNext () [0x00020] in C:\projects\ffimageloading\source\FFImageLoading.Common\DataResolvers\WrappedDataResolver.cs:22 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <657aa8fea4454dc898a9e5f379c58734>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <657aa8fea4454dc898a9e5f379c58734>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <657aa8fea4454dc898a9e5f379c58734>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <657aa8fea4454dc898a9e5f379c58734>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <657aa8fea4454dc898a9e5f379c58734>:0 
  at FFImageLoading.Work.ImageLoaderTask`3+<ShowPlaceholder>d__107[TDecoderContainer,TImageContainer,TImageView].MoveNext () [0x00299] in C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:445 
```
